#!/usr/bin/env python2
import rospy
import actionlib
from control_msgs.msg import FollowJointTrajectoryAction,FollowJointTrajectoryGoal
import numpy as np
from trajectory_msgs.msg import JointTrajectoryPoint
from robot_functions import *




if __name__ == '__main__':

 rospy.init_node("test_gazebo_gripper", disable_signals=True)
 gripper_client = actionlib.SimpleActionClient('hand_ee_controller/follow_joint_trajectory', FollowJointTrajectoryAction)
 
 print("Waiting for server...")
 gripper_client.wait_for_server()
 print("Connected to server")

 # Joint names
 jnames = ['joint_7', 'joint_8']
 # Joint Configuration
 q0 = np.array([0, 0])
 obj1=np.array([0.05, -0.05])
 obj2=np.array([0, 0])
 obj3=np.array([0.05, -0.05])

 g2 = FollowJointTrajectoryGoal()
 g2.trajectory.joint_names = jnames
 
 g2.trajectory.points = [JointTrajectoryPoint(positions=obj1, velocities=[0]*2,time_from_start=rospy.Duration(2.0))]
 gripper_client.send_goal(g2)
 gripper_client.wait_for_result()
 rospy.sleep(1)

 g2.trajectory.points = [ JointTrajectoryPoint(positions=obj2, velocities=[0]*2,time_from_start=rospy.Duration(2.0))]
 gripper_client.send_goal(g2)
 gripper_client.wait_for_result()
 rate = rospy.Rate(10)
 gripper_client.cancel_goal()




