gazebo_ros_control/pid_gains/joint_1: {p: 30000.0, i: 500.0, d: 900.0}
gazebo_ros_control/pid_gains/joint_2: {p: 30000.0, i: 500.0, d: 800.0}
gazebo_ros_control/pid_gains/joint_3: {p: 15000.0, i: 300.0, d: 500.0}
gazebo_ros_control/pid_gains/joint_4: {p: 15000.0, i: 400.0, d: 700.0}
gazebo_ros_control/pid_gains/joint_5: {p: 10000.0, i: 300.0, d: 700.0}
gazebo_ros_control/pid_gains/joint_6: {p: 10000.0, i: 300.0, d: 700.0}
gazebo_ros_control/pid_gains/joint_7: {p: 5000.0, i: 50, d: 10}
gazebo_ros_control/pid_gains/joint_8: {p: 5000.0, i: 50, d: 10}
